include = ['pyproject.toml', 'src/**/*.py', 'tests/**/*.py']
exclude = [
    '*.egg-info',
    '*.pyi',
    'build',
    'dist',
    '.tox',
    '.git',
    'venv',
    '.venv',
    '.mypy_cache',
    '.pytest_cache',
    '.ruff_cache',
]
line-length = 78
indent-width = 4
target-version = 'py38'

[lint]
select = [
    'B',      # flake8-bugbear
    'C4',     # flake8-comprehensions
    'D',      # pydocstyle
    'E',      # pycodestyle (Error)
    'F',      # Pyflakes
    'I',      # isort
    'PYI006', # flake8-pyi
    'RUF100', # unused noqa (auto-fixable)
    'T10',    # flake8-debugger
    'T20',    # flake8-print
    'UP',     # pyupgrade
    'YTT',    # flake8-2020
]

ignore  = [
    #### specific rules
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D105',
    'D106',
    'D107',
    'D203',
    'D205',
    'D211',
    'D213',
    'D401',
    'E203',
    'E266',
    'E501',
    # 'F401',
    'F403',
    'D403',
]
fixable = ['A', 'B', 'C4', 'E', 'F', 'I', 'TID', 'UP', 'D400', 'D415']
unfixable = []
flake8-quotes = {inline-quotes = 'single', multiline-quotes = 'double', docstring-quotes = 'double'}
dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$'

[format]
indent-style = 'space'
skip-magic-trailing-comma = false
line-ending = 'auto'
docstring-code-format = false
docstring-code-line-length = 'dynamic'

[lint.isort]
# required-imports = ['from __future__ import annotations']

[lint.mccabe]
max-complexity = 10

[lint.per-file-ignores]
'__init__.py' = ['F401']
